import { BriefcaseBusiness, ChevronDown, CircleAlert, FileCheck2, GraduationCap, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import PageShell from './PageShell'
import { AnimatedNumber, Avatar, Badge, Card, EmptyState, InlineFeedback, PrimaryButton, SecondaryButton, Skeleton } from './primitives'
import { useEmployeeRequestResource } from '../../hooks/useEmployeeRequestResource'
import { parseEmployeeRequestDetail, parseEmployeeTrustCard } from '../../lib/employeeDetailContract'
import { getEmployeeWorkflowState } from '../../lib/employeeWorkflow'
import { friendlyErrorMessage } from '../../lib/requestSafety'
import RefAILogo from '../branding/RefAILogo'
import { educationLines } from '../../lib/education'
import ClaimVerificationPanel from './ClaimVerificationPanel'
import TrustScoreExplanation from './TrustScoreExplanation'

export default function AuthenticatedTrustCardDetails({ requestId }: { requestId: string }) {
  const navigate = useNavigate()
  const detailResource = useEmployeeRequestResource(`/referral/employee/requests/${requestId}`, parseEmployeeRequestDetail)
  const cardResource = useEmployeeRequestResource(detailResource.data?.trustCardExists ? `/referral/employee/requests/${requestId}/trust-card` : null, parseEmployeeTrustCard)
  const detail = detailResource.data
  const card = cardResource.data
  const workflow = getEmployeeWorkflowState({ hasAssignedRequest: Boolean(detail), resumeExists: detail?.resumeExists, trustCardExists: Boolean(card), status: detail?.status })

  if (detailResource.loading) return <PageShell eyebrow="Trust Card details" title="Loading persisted Trust Card" description="Verifying request access and loading persisted evidence."><Skeleton className="h-[30rem] rounded-2xl" /></PageShell>
  if (detailResource.error || !detail) return <PageShell eyebrow="Trust Card details" title="Trust Card access unavailable" description="RefAI could not verify access to this assigned request."><InlineFeedback tone="error">{friendlyErrorMessage(detailResource.error, 'This request was not found or is not assigned to your Employee account.')}</InlineFeedback><EmptyState className="mt-6" icon={ShieldCheck} title="Unable to verify Trust Card access" description="Retry authorization or return to your queue." action={<div className="flex gap-2"><PrimaryButton onClick={detailResource.retry}>Retry</PrimaryButton><SecondaryButton onClick={() => navigate('/employee/dashboard')}>Back to Queue</SecondaryButton></div>} /></PageShell>
  if (cardResource.loading) return <PageShell eyebrow="Trust Card details" title="Loading persisted Trust Card" description="Verifying request access and loading persisted evidence."><Skeleton className="h-[30rem] rounded-2xl" /></PageShell>
  if (cardResource.error) return <PageShell eyebrow="Trust Card details" title="Trust Card unavailable" description="No readable persisted Trust Card was returned for this request."><InlineFeedback tone="error">{friendlyErrorMessage(cardResource.error, 'No persisted Trust Card is available for this assigned request.')}</InlineFeedback><EmptyState className="mt-6" icon={ShieldCheck} title="Trust Card could not be opened" description="Retry the authorized read or return to candidate review." action={<div className="flex gap-2"><PrimaryButton onClick={cardResource.retry}><RefreshCw className="mr-2 size-4" />Retry</PrimaryButton><SecondaryButton onClick={() => navigate(`/employee/review/${requestId}`)}>Back to Candidate</SecondaryButton></div>} /></PageShell>
  if (!card) return <PageShell eyebrow="Trust Card details" title="Trust Card unavailable" description="No readable persisted Trust Card was returned for this request."><EmptyState icon={ShieldCheck} title="No persisted Trust Card is available" description="This assigned referral request does not currently have a readable Trust Card." action={<PrimaryButton onClick={() => navigate(`/employee/review/${requestId}`)}>Back to Candidate</PrimaryButton>} /></PageShell>

  const educationDetails = educationLines(card.education)
  const strongestEvidence = card.strengths?.[0] || card.evidence?.[0] || 'No structured evidence summary was saved for this card.'
  const biggestGap = card.missingRequirements?.[0]?.requirement || card.riskSignals?.[0] || 'No primary evidence gap was recorded.'
  const matchedSkills = card.matchedSkills?.slice(0, 6) ?? []
  const explainableScore = card.trustScore !== null && card.scoreBreakdown?.length ? { trustScore: card.trustScore, scoreBreakdown: card.scoreBreakdown, scoreFormula: card.scoreFormula, scoreVersion: card.scoreVersion, analysisReliability: card.analysisReliability } : undefined

  return <PageShell eyebrow="Candidate intelligence" title={`Evaluate ${card.studentName || 'the candidate'}'s evidence`} description={`${card.targetRole} at ${card.targetCompany}. This persisted credential is available only for the assigned request.`} action={<div className="flex flex-wrap gap-2"><SecondaryButton onClick={() => navigate(`/employee/resume/${requestId}`)} disabled={!workflow.canOpenResume} disabledReason="No stored resume is available">Open resume</SecondaryButton><PrimaryButton onClick={() => navigate(`/employee/decision/${requestId}`)} disabled={!workflow.canMakeDecision} disabledReason="This request already has a recorded outcome">{workflow.canMakeDecision ? 'Make referral decision' : 'Decision unavailable'}</PrimaryButton></div>}>
    <Card className="overflow-hidden border-slate-800 bg-slate-950 text-white shadow-[0_24px_60px_-32px_rgba(15,23,42,0.85)]">
      <div className="grid gap-6 p-6 sm:p-8 lg:grid-cols-[1.15fr_0.85fr] lg:gap-10 lg:p-10">
        <div><div className="flex items-center justify-between gap-3"><RefAILogo inverse markClassName="size-9" wordmarkClassName="text-base font-semibold" subtitle="Candidate Trust Card" subtitleClassName="text-xs text-slate-400" /><Badge className="border-white/10 bg-white/10 text-white">Assigned request</Badge></div><div className="mt-7 flex items-center gap-4"><Avatar initials={card.studentName?.slice(0, 2).toUpperCase() || '—'} size="lg" className="border-4 border-white/10 bg-white text-black" /><div className="min-w-0"><h2 className="truncate text-2xl font-semibold tracking-tight">{card.studentName || 'Candidate'}</h2><p className="mt-1 truncate text-sm text-slate-400">{card.targetRole}</p></div></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-300"><span className="inline-flex items-center gap-1.5"><BriefcaseBusiness className="size-3.5 text-slate-500" />{card.targetCompany}</span><span className="inline-flex items-start gap-1.5"><GraduationCap className="mt-0.5 size-3.5 shrink-0 text-slate-500" />{educationDetails.length ? educationDetails.join(' · ') : 'Education not recorded'}</span></div></div>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-2"><div className="col-span-2 rounded-2xl border border-white/10 bg-white/[0.06] p-5 sm:col-span-1 lg:col-span-2"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">Candidate Trust Score</p><div className="mt-2 flex items-end gap-2"><p className="text-5xl font-semibold tracking-tight tabular-nums">{card.trustScore === null ? '—' : <AnimatedNumber value={card.trustScore} />}</p><span className="mb-1 text-sm text-slate-400">/100</span></div><p className="mt-2 text-xs text-slate-400">Five deterministic components. Advisory AI does not calculate this score.</p></div><div className="rounded-xl border border-white/10 bg-white/[0.04] p-3.5"><p className="text-[10px] font-semibold uppercase tracking-[0.13em] text-slate-500">Reliability</p><p className="mt-2 text-sm font-semibold text-white">{card.analysisReliability?.label || 'Not recorded'}</p></div><div className="rounded-xl border border-white/10 bg-white/[0.04] p-3.5"><p className="text-[10px] font-semibold uppercase tracking-[0.13em] text-slate-500">Readiness</p><p className="mt-2 text-sm font-semibold text-white">{card.readiness || 'Not recorded'}</p></div></div>
      </div>
      <div className="grid border-t border-white/10 bg-black/15 lg:grid-cols-[1fr_1fr_0.8fr]"><div className="border-b border-white/10 p-5 lg:border-b-0 lg:border-r lg:border-white/10 lg:px-7"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-emerald-300">Strongest evidence</p><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-100">{strongestEvidence}</p></div><div className="border-b border-white/10 p-5 lg:border-b-0 lg:border-r lg:border-white/10 lg:px-7"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-amber-200">Biggest concern</p><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-100">{biggestGap}</p></div><div className="p-5 lg:px-7"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-slate-400">Relevant skills</p><div className="mt-2 flex flex-wrap gap-1.5">{matchedSkills.length ? matchedSkills.map((skill) => <span key={skill} className="rounded-full border border-white/10 bg-white/5 px-2 py-1 text-[11px] font-medium text-slate-200">{skill}</span>) : <span className="text-xs text-slate-400">No structured skills</span>}</div></div></div>
    </Card>

    <div className="mt-5 grid gap-3 lg:grid-cols-3"><details className="group rounded-xl border border-slate-200 bg-white open:shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3.5 text-sm font-semibold text-slate-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-inset"><span className="inline-flex items-center gap-2"><Sparkles className="size-4" />Quick resume summary</span><ChevronDown className="size-4 text-slate-400 transition-transform group-open:rotate-180" /></summary><div className="border-t border-slate-200 p-4 text-sm leading-6 text-slate-600">{card.summary || 'No saved resume summary is available for this request.'}</div></details><details className="group rounded-xl border border-slate-200 bg-white open:shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3.5 text-sm font-semibold text-slate-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-inset"><span className="inline-flex items-center gap-2"><FileCheck2 className="size-4" />Proof verification</span><ChevronDown className="size-4 text-slate-400 transition-transform group-open:rotate-180" /></summary><div id="claim-verification" className="border-t border-slate-200 p-3 scroll-mt-24"><ClaimVerificationPanel requestId={requestId} /></div></details><details className="group rounded-xl border border-slate-200 bg-white open:shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3.5 text-sm font-semibold text-slate-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-inset"><span className="inline-flex items-center gap-2"><CircleAlert className="size-4" />Evidence details</span><ChevronDown className="size-4 text-slate-400 transition-transform group-open:rotate-180" /></summary><div className="border-t border-slate-200 p-4"><div className="flex flex-wrap gap-2">{card.missingRequirements?.length ? card.missingRequirements.map((item) => <Badge key={item.requirement} tone="warning">{item.requirement}</Badge>) : <span className="text-xs text-slate-500">No missing requirements recorded.</span>}</div>{card.evidence?.length ? <ul className="mt-4 space-y-2">{card.evidence.map((item) => <li key={item} className="text-sm leading-6 text-slate-600">• {item}</li>)}</ul> : null}{card.riskSignals?.length ? <ul className="mt-4 space-y-2 border-t border-slate-100 pt-4">{card.riskSignals.map((item) => <li key={item} className="text-sm leading-6 text-slate-600">• {item}</li>)}</ul> : null}</div></details></div>
    <details className="group mt-5 rounded-xl border border-slate-200 bg-white open:shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-5 py-4 text-sm font-semibold text-slate-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-inset"><span className="inline-flex items-center gap-2"><ShieldCheck className="size-4" />Score calculation and supporting receipts</span><ChevronDown className="size-4 text-slate-400 transition-transform group-open:rotate-180" /></summary><div className="border-t border-slate-200 p-3 sm:p-5"><TrustScoreExplanation trustCard={explainableScore} /><p className="mt-3 text-xs text-slate-500">Generated {card.generatedAt ? new Date(card.generatedAt).toLocaleString() : 'date unavailable'}{card.scoreVersion ? ` · ${card.scoreVersion}` : ''}</p></div></details>
  </PageShell>
}
