import { CheckCircle2, GraduationCap, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import PageShell from './PageShell'
import { Badge, Card, EmptyState, InlineFeedback, PrimaryButton, ProgressBar, SecondaryButton, Skeleton } from './primitives'
import { useEmployeeRequestResource } from '../../hooks/useEmployeeRequestResource'
import { parseEmployeeRequestDetail, parseEmployeeTrustCard } from '../../lib/employeeDetailContract'
import { getEmployeeWorkflowState } from '../../lib/employeeWorkflow'
import { friendlyErrorMessage } from '../../lib/requestSafety'
import RefAILogo from '../branding/RefAILogo'
import { educationLines } from '../../lib/education'
import ClaimVerificationPanel from './ClaimVerificationPanel'
import TrustScoreExplanation from './TrustScoreExplanation'

export default function AuthenticatedTrustCardDetails({ requestId }: { requestId: string }) {
  const navigate = useNavigate()
  const detailResource = useEmployeeRequestResource(`/referral/employee/requests/${requestId}`, parseEmployeeRequestDetail)
  const cardResource = useEmployeeRequestResource(detailResource.data?.trustCardExists ? `/referral/employee/requests/${requestId}/trust-card` : null, parseEmployeeTrustCard)
  const detail = detailResource.data
  const card = cardResource.data
  const workflow = getEmployeeWorkflowState({ hasAssignedRequest: Boolean(detail), resumeExists: detail?.resumeExists, trustCardExists: Boolean(card), status: detail?.status })

  if (detailResource.loading) return <PageShell eyebrow="Trust Card details" title="Loading persisted Trust Card" description="Verifying request access and loading persisted evidence."><Skeleton className="h-[30rem] rounded-2xl" /></PageShell>
  if (detailResource.error || !detail) return <PageShell eyebrow="Trust Card details" title="Trust Card access unavailable" description="RefAI could not verify access to this assigned request."><InlineFeedback tone="error">{friendlyErrorMessage(detailResource.error, 'This request was not found or is not assigned to your Employee account.')}</InlineFeedback><EmptyState className="mt-6" icon={ShieldCheck} title="Unable to verify Trust Card access" description="Retry authorization or return to your queue." action={<div className="flex gap-2"><PrimaryButton onClick={detailResource.retry}>Retry</PrimaryButton><SecondaryButton onClick={() => navigate('/employee/dashboard')}>Back to Queue</SecondaryButton></div>} /></PageShell>

  if (cardResource.loading) return <PageShell eyebrow="Trust Card details" title="Loading persisted Trust Card" description="Verifying request access and loading persisted evidence."><Skeleton className="h-[30rem] rounded-2xl" /></PageShell>
  if (cardResource.error) return <PageShell eyebrow="Trust Card details" title="Trust Card unavailable" description="No readable persisted Trust Card was returned for this request."><InlineFeedback tone="error">{friendlyErrorMessage(cardResource.error, 'No persisted Trust Card is available for this assigned request.')}</InlineFeedback><EmptyState className="mt-6" icon={ShieldCheck} title="Trust Card could not be opened" description="Retry the authorized read or return to candidate review." action={<div className="flex gap-2"><PrimaryButton onClick={cardResource.retry}><RefreshCw className="mr-2 size-4" />Retry</PrimaryButton><SecondaryButton onClick={() => navigate(`/employee/review/${requestId}`)}>Back to Candidate</SecondaryButton></div>} /></PageShell>
  if (!card) return <PageShell eyebrow="Trust Card details" title="Trust Card unavailable" description="No readable persisted Trust Card was returned for this request."><EmptyState icon={ShieldCheck} title="No persisted Trust Card is available" description="This assigned referral request does not currently have a readable Trust Card." action={<PrimaryButton onClick={() => navigate(`/employee/review/${requestId}`)}>Back to Candidate</PrimaryButton>} /></PageShell>

  const scores = [['Trust Score', card.trustScore], ['Overall Match', card.overallMatch], ['Role Fit', card.roleFit], ['Proof Score', card.proofScore], ['Gap Score', card.gapScore]] as const
  const educationDetails = educationLines(card.education)
  const explainableScore = card.trustScore !== null && card.scoreBreakdown?.length ? {
    trustScore: card.trustScore,
    scoreBreakdown: card.scoreBreakdown,
    scoreFormula: card.scoreFormula,
    scoreVersion: card.scoreVersion,
    analysisReliability: card.analysisReliability,
  } : undefined
  return <PageShell eyebrow="Trust Card details" title={`Evaluate ${card.studentName || 'the candidate'}'s evidence`} description={`${card.targetRole} at ${card.targetCompany}. This is the persisted Trust Card linked to the assigned request.`} action={<div className="flex flex-wrap gap-2"><SecondaryButton onClick={() => navigate(`/employee/resume/${requestId}`)} disabled={!workflow.canOpenResume} disabledReason="No stored resume is available">Back to Resume</SecondaryButton><PrimaryButton onClick={() => navigate(`/employee/decision/${requestId}`)} disabled={!workflow.canMakeDecision} disabledReason="This request already has a recorded outcome">{workflow.canMakeDecision ? 'Make referral decision' : 'Decision unavailable'}</PrimaryButton></div>}>
    <div className="mb-6"><TrustScoreExplanation isDemoMode={false} trustCard={explainableScore} /></div>
    <div id="claim-verification" className="mb-6 scroll-mt-24"><ClaimVerificationPanel requestId={requestId} /></div>
    <div className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><Card className="bg-slate-950 p-6 text-white sm:p-8"><div className="flex items-center justify-between"><RefAILogo inverse markClassName="size-10" wordmarkClassName="text-base font-semibold" subtitle="Candidate Trust Card" subtitleClassName="text-sm text-slate-400" /><Badge className="border-white/10 bg-white/10 text-white">Employee view</Badge></div><p className="mt-10 text-sm text-slate-400">Trust Score</p><p className="mt-2 text-5xl font-semibold">{card.trustScore ?? '—'}</p><p className="mt-6 text-sm leading-7 text-slate-300">{card.readiness || 'Readiness unavailable'}</p><div className="mt-5 flex items-start gap-2 text-sm leading-6 text-slate-300"><GraduationCap className="mt-1 size-4 shrink-0 text-slate-400" /><div>{educationDetails.length ? educationDetails.map((line) => <p key={line}>{line}</p>) : <p>Educational data not available</p>}</div></div><p className="mt-3 text-xs text-slate-500">Generated {card.generatedAt ? new Date(card.generatedAt).toLocaleString() : 'date unavailable'}</p></Card><Card className="p-6 sm:p-8"><div className="flex items-center justify-between"><h3 className="text-xl font-semibold">Referral evidence summary</h3><Badge tone={card.recommendation === 'Ready for referral' ? 'success' : 'warning'}>{card.recommendation || 'Recommendation unavailable'}</Badge></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{scores.map(([label, score]) => <div key={label} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3 text-sm"><span className="text-slate-500">{label}</span><span className="font-semibold">{score === null ? 'Unavailable' : `${score}%`}</span></div>{score !== null ? <div className="mt-3"><ProgressBar value={score} /></div> : null}</div>)}</div><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-sm font-semibold">Analysis Reliability · {card.analysisReliability?.label ?? 'Not recorded'}</p>{card.analysisReliability ? <><p className="mt-2 text-sm leading-6 text-slate-700">{card.analysisReliability.basis}</p><p className="mt-2 text-xs leading-5 text-slate-500"><span className="font-semibold">Limitations:</span> {card.analysisReliability.limitations}</p></> : <p className="mt-2 text-xs text-slate-500">This older saved Trust Card does not include an Analysis Reliability assessment.</p>}</div></Card></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="p-6 sm:p-8"><div className="flex items-center gap-3"><CheckCircle2 className="size-5" /><h3 className="text-lg font-semibold">Strengths and matched skills</h3></div><div className="mt-5 flex flex-wrap gap-2">{card.matchedSkills?.map((skill) => <Badge key={skill} tone="success">{skill}</Badge>)}</div><ul className="mt-5 space-y-3">{card.strengths?.map((item) => <li key={item} className="rounded-xl border border-slate-200 p-4 text-sm leading-6">{item}</li>)}</ul></Card><Card className="p-6 sm:p-8"><div className="flex items-center gap-3"><Sparkles className="size-5" /><h3 className="text-lg font-semibold">AI summary and evidence</h3></div><p className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-5 text-sm leading-7">{card.summary || 'Summary unavailable.'}</p><ul className="mt-5 space-y-3">{card.evidence?.map((item) => <li key={item} className="rounded-xl border border-slate-200 p-4 text-sm leading-6">{item}</li>)}</ul></Card><Card className="p-6 sm:p-8"><h3 className="text-lg font-semibold">Missing requirements</h3><div className="mt-5 flex flex-wrap gap-2">{card.missingRequirements?.map((item) => <Badge key={item.requirement} tone="warning">{item.requirement}</Badge>) || <p className="text-sm text-slate-500">Unavailable</p>}</div></Card><Card className="p-6 sm:p-8"><h3 className="text-lg font-semibold">Risk signals and score formula</h3><ul className="mt-5 space-y-3">{card.riskSignals?.map((item) => <li key={item} className="rounded-xl border border-slate-200 p-4 text-sm leading-6">{item}</li>)}</ul><p className="mt-5 text-sm leading-6 text-slate-600">{card.scoreFormula || 'Score formula unavailable.'}</p></Card></div>
  </PageShell>
}
