import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../../lib/apiClient'
import { friendlyErrorMessage } from '../../lib/requestSafety'
import { InlineFeedback, PrimaryButton } from './primitives'

type Outcome = 'approved' | 'declined' | 'more_info_requested'
const options: Record<Outcome, Array<[string, string]>> = {
  approved: [['suitable_profile', 'Suitable profile'], ['strong_evidence', 'Strong evidence'], ['relevant_role_alignment', 'Relevant role alignment'], ['will_refer_externally', 'Will refer externally'], ['additional_details_required_first', 'Additional details required first']],
  declined: [['insufficient_evidence', 'Insufficient evidence'], ['skill_mismatch', 'Skill mismatch'], ['experience_gap', 'Experience gap'], ['resume_quality', 'Resume quality'], ['employee_company_policy', 'Employee/company referral policy'], ['opportunity_unavailable', 'Opportunity unavailable or filled'], ['other', 'Other']],
  more_info_requested: [['clarification_required', 'Clarification required']],
}

export default function EmployeeDecisionPanel({ requestId, disabled }: { requestId: string; disabled: boolean }) {
  const navigate = useNavigate(); const [outcome, setOutcome] = useState<Outcome>('approved'); const [reason, setReason] = useState('suitable_profile'); const [note, setNote] = useState(''); const [question, setQuestion] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const selectOutcome = (value: Outcome) => { setOutcome(value); setReason(options[value][0][0]); setError(null) }
  const save = async () => { if (saving || disabled || (outcome === 'more_info_requested' && !question.trim())) return; setSaving(true); setError(null); try { await api.patch(`/referral/requests/${requestId}/decision`, { status: outcome, reason, note: note.trim() || null, question: outcome === 'more_info_requested' ? question.trim() : null }); navigate(`/employee/decision/${requestId}/confirmation`) } catch (cause) { setError(friendlyErrorMessage(cause, 'The decision could not be saved.')) } finally { setSaving(false) } }
  return <div className="mt-4"><div className="grid grid-cols-3 gap-1 rounded-xl bg-slate-100 p-1">{([['approved', 'Approve'], ['more_info_requested', 'More info'], ['declined', 'Decline']] as Array<[Outcome, string]>).map(([value, label]) => <button key={value} type="button" onClick={() => selectOutcome(value)} className={`min-h-9 rounded-lg px-2 text-xs font-semibold focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 ${outcome === value ? 'bg-white text-slate-950 shadow-sm' : 'text-slate-600'}`}>{label}</button>)}</div><label className="mt-3 block text-xs font-semibold text-slate-700">Structured reason<select value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-slate-300 bg-white px-2 text-sm font-normal">{options[outcome].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{outcome === 'more_info_requested' ? <label className="mt-3 block text-xs font-semibold text-slate-700">Question for student<textarea value={question} onChange={(event) => setQuestion(event.target.value)} maxLength={1000} className="mt-1 min-h-20 w-full rounded-lg border border-slate-300 p-2 text-sm font-normal" placeholder="Ask for the specific missing evidence." /></label> : null}<label className="mt-3 block text-xs font-semibold text-slate-700">Private employee note <span className="font-normal text-slate-500">(optional)</span><textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={2000} className="mt-1 min-h-16 w-full rounded-lg border border-slate-300 p-2 text-sm font-normal" placeholder="Never shared with the student." /></label>{error ? <div className="mt-3"><InlineFeedback tone="error">{error}</InlineFeedback></div> : null}<PrimaryButton className="mt-4 w-full" onClick={save} loading={saving} disabled={disabled || (outcome === 'more_info_requested' && !question.trim())}>Record {outcome === 'approved' ? 'approval' : outcome === 'declined' ? 'decline' : 'information request'}</PrimaryButton><p className="mt-2 text-[11px] leading-4 text-slate-500">The student receives a respectful, structured summary. Private notes are never shown. A decline does not change the Candidate Trust Score.</p></div>
}
