import { ArrowUpRight, RefreshCw, Sparkles, TrendingUp } from 'lucide-react'
import { useState } from 'react'
import { api } from '../../lib/apiClient'
import { friendlyErrorMessage } from '../../lib/requestSafety'
import type { ImprovementSimulatorResult } from '../../types'
import { Badge, Card, EmptyState, InlineFeedback, SecondaryButton, Skeleton } from './primitives'

export default function ImprovementSimulatorPanel() {
  const [result, setResult] = useState<ImprovementSimulatorResult | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [selectedSkills, setSelectedSkills] = useState<string[]>([])
  const [addProjectEvidence, setAddProjectEvidence] = useState(false)
  const [simulating, setSimulating] = useState(false)
  const load = async () => {
    setLoading(true); setError(null)
    try { const { data } = await api.get<ImprovementSimulatorResult>('/resume/analysis/improvement-simulator', { headers: { 'X-RefAI-No-Retry': 'true' } }); setResult(data) }
    catch (cause) { setError(friendlyErrorMessage(cause, 'Improvement opportunities could not be loaded.')) }
    finally { setLoading(false) }
  }
  const clearEstimate = () => setResult((current) => current?.simulation ? { ...current, simulation: null } : current)
  const toggleSkill = (skill: string) => { clearEstimate(); setSelectedSkills((current) => current.includes(skill) ? current.filter((item) => item !== skill) : [...current, skill]) }
  const toggleProjectEvidence = () => { clearEstimate(); setAddProjectEvidence((current) => !current) }
  const simulate = async () => {
    if (!selectedSkills.length && !addProjectEvidence) return
    setSimulating(true); setError(null)
    try { const { data } = await api.post<ImprovementSimulatorResult>('/resume/analysis/improvement-simulator/simulate', { skillEvidence: selectedSkills, addProjectEvidence }); setResult(data) }
    catch (cause) { setError(friendlyErrorMessage(cause, 'The estimate could not be calculated.')) }
    finally { setSimulating(false) }
  }

  const currentScore = result?.simulation?.currentScore ?? result?.currentScore
  const simulatedScore = result?.simulation?.simulatedScore ?? currentScore
  const hasSelection = selectedSkills.length > 0 || addProjectEvidence

  return <Card className="overflow-hidden p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-slate-100 text-slate-800"><TrendingUp className="size-4" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Smart Improvement Simulator</p><h3 className="mt-1 text-xl font-semibold tracking-tight">Explore truthful evidence improvements</h3></div></div><Badge tone="info">Simulation only</Badge></div>
    {!result && !loading && !error ? <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50/70 p-4"><div><p className="text-sm font-semibold text-slate-900">Ready when you are</p><p className="mt-1 text-xs leading-5 text-slate-500">Load your saved evidence options, then choose an improvement to estimate.</p></div><SecondaryButton onClick={load}><Sparkles className="mr-2 size-4" />Open simulator</SecondaryButton></div> : null}
    {loading ? <div className="mt-5 space-y-3"><Skeleton className="h-24" /><Skeleton className="h-20" /></div> : null}
    {error ? <div className="mt-5"><InlineFeedback tone="error">{error}</InlineFeedback><SecondaryButton className="mt-3" onClick={load}><RefreshCw className="mr-2 size-4" />Retry</SecondaryButton></div> : null}
    {result ? <><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto_1fr]"><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-500">Current score</p><p className="mt-1 text-3xl font-semibold tabular-nums text-slate-950">{currentScore ?? '—'}</p></div><div className="hidden items-center justify-center text-slate-400 sm:flex">→</div><div className={`rounded-xl border p-4 ${result.simulation ? 'border-slate-300 bg-slate-100' : 'border-dashed border-slate-300 bg-slate-50'}`}><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-500">Simulated score</p><div className="mt-1 flex items-baseline gap-2"><p className="text-3xl font-semibold tabular-nums text-slate-950">{result.simulation ? simulatedScore : '—'}</p>{result.simulation ? <span className="text-sm font-semibold text-slate-700">{result.simulation.difference >= 0 ? '+' : ''}{result.simulation.difference}</span> : null}</div></div></div><p className="mt-2 text-xs text-slate-500">Estimates use hypothetical evidence only. They do not update your profile, resume, or saved scores.</p>
      {result.intelligenceSnapshot ? <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex items-start gap-2"><Sparkles className="mt-0.5 size-4 text-slate-700" /><div><p className="text-sm font-semibold text-slate-900">Choose an improvement to estimate</p><p className="mt-1 text-xs leading-5 text-slate-500">Only options supported by your current analysis are shown.</p></div></div><div className="mt-3 flex flex-wrap gap-2">{result.intelligenceSnapshot.availableSkillScenarios.map((scenario) => { const selected = selectedSkills.includes(scenario.skill); return <button key={scenario.skill} type="button" aria-pressed={selected} onClick={() => toggleSkill(scenario.skill)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold transition focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-offset-2 ${selected ? 'border-slate-950 bg-slate-950 text-white' : 'border-slate-200 bg-white text-slate-700 hover:border-slate-400'}`}>Add evidence: {scenario.skill}<span className={`ml-1.5 font-medium ${selected ? 'text-slate-300' : 'text-slate-400'}`}>{scenario.priority}</span></button> })}<button type="button" aria-pressed={addProjectEvidence} onClick={toggleProjectEvidence} className={`rounded-full border px-3 py-1.5 text-xs font-semibold transition focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-offset-2 ${addProjectEvidence ? 'border-slate-950 bg-slate-950 text-white' : 'border-slate-200 bg-white text-slate-700 hover:border-slate-400'}`}>Strengthen project evidence</button></div><div className="mt-4 flex flex-wrap items-center gap-3"><SecondaryButton onClick={simulate} disabled={simulating || !hasSelection}><Sparkles className="mr-2 size-4" />{simulating ? 'Estimating…' : 'Estimate change'}</SecondaryButton>{hasSelection ? <span className="text-xs text-slate-500">{selectedSkills.length + Number(addProjectEvidence)} hypothetical improvement{selectedSkills.length + Number(addProjectEvidence) === 1 ? '' : 's'} selected</span> : <span className="text-xs text-slate-500">Select one or more options to begin.</span>}</div></div> : null}
      {result.simulation ? <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-600">Estimated result — not a saved score</p><p className="mt-1 text-sm font-semibold text-slate-900">Affected academic intelligence components</p></div><Badge tone="neutral">Hybrid intelligence</Badge></div><div className="mt-3 space-y-2">{result.simulation.affectedComponents.map((component) => <div key={component.key} className="grid gap-1 rounded-lg border border-slate-200 bg-white/70 px-3 py-2.5 sm:grid-cols-[minmax(0,1fr)_auto]"><p className="text-xs font-semibold text-slate-800">{component.label} <span className="font-normal text-slate-500">{component.currentScore} → {component.simulatedScore}</span></p><p className="text-xs leading-5 text-slate-600 sm:text-right">{component.whyChanged}</p></div>)}</div>{result.simulation.whyScoreChanged.slice(0, 2).map((item) => <p key={item} className="mt-2 text-xs leading-5 text-slate-600">• {item}</p>)}{result.simulation.limitations.slice(0, 1).map((item) => <p key={item} className="mt-2 text-[11px] leading-5 text-slate-500">{item}</p>)}</div> : null}
      {result.suggestions.length ? <section className="mt-5"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">Highest-potential evidence actions</p><p className="mt-1 text-xs text-slate-500">Potential points are estimates, not guarantees.</p></div><Badge tone="neutral">Up to {result.totalMaximumPotentialPoints}</Badge></div><div className="mt-3 divide-y divide-slate-200 overflow-hidden rounded-xl border border-slate-200 bg-white">{result.suggestions.slice(0, 3).map((suggestion) => <details key={suggestion.componentKey} className="group"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-3.5 py-3 focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-inset"><div className="min-w-0"><p className="text-sm font-semibold text-slate-900">{suggestion.recommendedAction}</p><p className="mt-0.5 truncate text-xs text-slate-500">{suggestion.affectedComponent}</p></div><div className="flex items-center gap-2"><Badge tone="info">Up to +{suggestion.maximumPotentialPoints}</Badge><ArrowUpRight className="size-4 text-slate-400 transition-transform group-open:rotate-45" /></div></summary><div className="border-t border-slate-100 bg-slate-50 px-3.5 py-3"><p className="text-xs leading-5 text-slate-600">{suggestion.missingEvidence[0] || suggestion.limitation}</p></div></details>)}</div></section> : <EmptyState className="mt-5" icon={TrendingUp} title="No remaining component capacity" description="The current deterministic breakdown does not expose additional potential points. Preserve truthful, specific evidence when updating the resume." />}
      {result.comparison ? <details className="mt-4 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"><summary className="cursor-pointer text-sm font-semibold text-slate-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-slate-950 focus-visible:ring-offset-2">Previous analysis comparison · {result.comparison.previousScore} → {result.comparison.currentScore}</summary><div className="mt-3 space-y-2">{result.comparison.componentDeltas.filter((item) => item.delta !== 0 || item.evidenceCausingChange.length).map((item) => <p key={item.componentKey} className="text-xs leading-5 text-slate-600"><span className="font-semibold text-slate-800">{item.component}:</span> {item.delta >= 0 ? '+' : ''}{item.delta}. {item.evidenceCausingChange[0] || 'No evidence change was recorded.'}</p>)}</div></details> : null}
    </> : null}
  </Card>
}
