import { Award, BriefcaseBusiness, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import RefAILogo from '../components/branding/RefAILogo'
import { Badge, Card, Skeleton } from '../components/dashboard/primitives'
import { api } from '../lib/apiClient'

type Passport = { candidateName?: string; targetRole?: string; trustScore?: number; hybridScore?: number; fuzzySuitabilityScore?: number; verifiedSkills: string[]; verifiedEvidenceCount?: number; strongestVerifiedEvidence: string[]; reliability?: { label?: string; basis?: string; limitations?: string }; algorithmVersion?: string; generatedAt?: string; expiresAt?: string }

export default function TrustPassport() {
  const { token } = useParams(); const [passport, setPassport] = useState<Passport | null>(null); const [failed, setFailed] = useState(false)
  useEffect(() => { if (!token) { setFailed(true); return }; api.get<Passport>(`/trust-card/passport/public/${encodeURIComponent(token)}`).then(({ data }) => setPassport(data)).catch(() => setFailed(true)) }, [token])
  if (failed) return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-5"><Card className="max-w-md p-8 text-center"><h1 className="text-xl font-semibold">Trust Passport unavailable</h1><p className="mt-2 text-sm leading-6 text-slate-600">This link may have expired, been revoked, or is not valid.</p></Card></main>
  if (!passport) return <main className="flex min-h-screen items-center justify-center bg-slate-100 p-5"><Card className="w-full max-w-2xl p-8"><Skeleton className="h-8 w-36" /><Skeleton className="mt-6 h-56 w-full" /></Card></main>
  const scores = [['Candidate Trust Score', passport.trustScore], ['Hybrid intelligence', passport.hybridScore], ['Fuzzy suitability', passport.fuzzySuitabilityScore]].filter((item): item is [string, number] => typeof item[1] === 'number')
  return <main className="min-h-screen bg-slate-100 px-4 py-8 sm:px-6 sm:py-12"><div className="mx-auto max-w-3xl"><Card className="overflow-hidden border-slate-800 bg-slate-950 text-white shadow-[0_28px_70px_-38px_rgba(15,23,42,0.9)]"><div className="p-6 sm:p-10"><RefAILogo inverse subtitle="Privacy-controlled Trust Passport" subtitleClassName="text-xs text-slate-400" /><div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-400">{passport.candidateName || 'Candidate'}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{passport.targetRole || 'Candidate credential'}</h1></div><Badge className="border-emerald-300/20 bg-emerald-300/10 text-emerald-200"><ShieldCheck className="mr-1 size-3.5" />Shared by candidate</Badge></div>{scores.length ? <div className="mt-8 grid gap-3 sm:grid-cols-3">{scores.map(([label, score]) => <div key={label} className="rounded-xl border border-white/10 bg-white/[0.06] p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.13em] text-slate-400">{label}</p><p className="mt-2 text-3xl font-semibold tabular-nums">{score}<span className="ml-1 text-sm text-slate-400">/100</span></p></div>)}</div> : null}</div><div className="grid border-t border-white/10 sm:grid-cols-2"><section className="p-6 sm:border-r sm:border-white/10"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-emerald-300"><Award className="size-4" />Verified evidence</p><p className="mt-3 text-sm text-slate-200">{passport.verifiedEvidenceCount ?? 0} evidence-backed item{passport.verifiedEvidenceCount === 1 ? '' : 's'} shared</p><div className="mt-4 flex flex-wrap gap-2">{passport.verifiedSkills.map((skill) => <Badge key={skill} className="border-white/10 bg-white/[0.06] text-slate-100">{skill}</Badge>)}</div>{passport.strongestVerifiedEvidence.map((item) => <p key={item} className="mt-3 text-xs leading-5 text-slate-300">• {item}</p>)}</section><section className="p-6"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-400"><BriefcaseBusiness className="size-4" />Analysis reliability</p><p className="mt-3 text-sm font-semibold">{passport.reliability?.label || 'Not shared'}</p>{passport.reliability?.basis ? <p className="mt-2 text-xs leading-5 text-slate-300">{passport.reliability.basis}</p> : null}{passport.reliability?.limitations ? <p className="mt-3 text-xs leading-5 text-slate-400">Limitation: {passport.reliability.limitations}</p> : null}</section></div><div className="border-t border-white/10 px-6 py-4 text-[11px] text-slate-500 sm:px-10">This is a candidate-controlled summary, not a hiring prediction. {passport.algorithmVersion ? `Algorithm: ${passport.algorithmVersion}.` : ''}</div></Card></div></main>
}
