-- Central simulated AI credits. Payments are intentionally not integrated.
create table if not exists public.refai_credit_accounts (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance integer not null default 10 check (balance >= 0), updated_at timestamptz not null default now()
);
create table if not exists public.refai_credit_operations (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade,
  action text not null, operation_key text not null, cost integer not null check (cost >= 0), status text not null check (status in ('processing','completed','refunded')),
  created_at timestamptz not null default now(), unique(user_id, operation_key)
);
create table if not exists public.refai_credit_ledger (
  id bigint generated always as identity primary key, user_id uuid not null references public.profiles(id) on delete cascade,
  operation_id uuid not null references public.refai_credit_operations(id) on delete restrict, action text not null,
  amount integer not null, balance_after integer not null check (balance_after >= 0), created_at timestamptz not null default now()
);
create table if not exists public.refai_ai_output_cache (
  user_id uuid not null references public.profiles(id) on delete cascade, input_key text not null check (input_key ~ '^[0-9a-f]{64}$'),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'), created_at timestamptz not null default now(), primary key(user_id, input_key)
);
alter table public.refai_credit_accounts enable row level security; alter table public.refai_credit_ledger enable row level security; alter table public.refai_credit_operations enable row level security; alter table public.refai_ai_output_cache enable row level security;
create policy refai_credit_accounts_read_own on public.refai_credit_accounts for select to authenticated using (user_id = auth.uid());
create policy refai_credit_ledger_read_own on public.refai_credit_ledger for select to authenticated using (user_id = auth.uid());
revoke all on public.refai_credit_accounts, public.refai_credit_ledger, public.refai_credit_operations, public.refai_ai_output_cache from anon, authenticated;
grant select on public.refai_credit_accounts, public.refai_credit_ledger to authenticated; grant all on public.refai_credit_accounts, public.refai_credit_ledger, public.refai_credit_operations, public.refai_ai_output_cache to service_role;
create or replace function public.get_refai_credit_balance(p_user_id uuid, p_free_credits integer) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_balance integer; begin insert into public.refai_credit_accounts(user_id,balance) values(p_user_id,greatest(0,p_free_credits)) on conflict do nothing; select balance into v_balance from public.refai_credit_accounts where user_id=p_user_id; return jsonb_build_object('balance',v_balance); end $$;
create or replace function public.reserve_refai_ai_credit(p_user_id uuid,p_action text,p_operation_key text,p_cost integer,p_free_credits integer) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_balance integer; v_op public.refai_credit_operations; begin insert into public.refai_credit_accounts(user_id,balance) values(p_user_id,greatest(0,p_free_credits)) on conflict do nothing; select * into v_op from public.refai_credit_operations where user_id=p_user_id and operation_key=p_operation_key; if v_op.id is not null then return jsonb_build_object('ok',v_op.status='processing','replay',true); end if; select balance into v_balance from public.refai_credit_accounts where user_id=p_user_id for update; if v_balance<p_cost then return jsonb_build_object('ok',false,'reason','no_credit'); end if; insert into public.refai_credit_operations(user_id,action,operation_key,cost,status) values(p_user_id,p_action,p_operation_key,p_cost,'processing') returning * into v_op; update public.refai_credit_accounts set balance=balance-p_cost,updated_at=now() where user_id=p_user_id returning balance into v_balance; insert into public.refai_credit_ledger(user_id,operation_id,action,amount,balance_after) values(p_user_id,v_op.id,p_action,-p_cost,v_balance); return jsonb_build_object('ok',true,'replay',false); end $$;
create or replace function public.finish_refai_ai_credit(p_user_id uuid,p_operation_key text,p_input_key text,p_payload jsonb,p_charge boolean) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_op public.refai_credit_operations; v_balance integer; begin select * into v_op from public.refai_credit_operations where user_id=p_user_id and operation_key=p_operation_key for update; if v_op.id is null then raise exception 'credit operation not found'; end if; insert into public.refai_ai_output_cache(user_id,input_key,payload) values(p_user_id,p_input_key,p_payload) on conflict (user_id,input_key) do update set payload=excluded.payload; if not p_charge and v_op.status='processing' then update public.refai_credit_accounts set balance=balance+v_op.cost,updated_at=now() where user_id=p_user_id returning balance into v_balance; insert into public.refai_credit_ledger(user_id,operation_id,action,amount,balance_after) values(p_user_id,v_op.id,v_op.action,v_op.cost,v_balance); update public.refai_credit_operations set status='refunded' where id=v_op.id; else update public.refai_credit_operations set status='completed' where id=v_op.id; end if; return jsonb_build_object('ok',true); end $$;
revoke all on function public.get_refai_credit_balance(uuid,integer), public.reserve_refai_ai_credit(uuid,text,text,integer,integer), public.finish_refai_ai_credit(uuid,text,text,jsonb,boolean) from public,anon,authenticated;
grant execute on function public.get_refai_credit_balance(uuid,integer), public.reserve_refai_ai_credit(uuid,text,text,integer,integer), public.finish_refai_ai_credit(uuid,text,text,jsonb,boolean) to service_role;
create or replace function public.purchase_refai_credits(p_user_id uuid,p_plan text,p_operation_key text,p_credits integer,p_free_credits integer) returns jsonb language plpgsql security definer set search_path=public as $$ declare v_balance integer; v_op public.refai_credit_operations; begin insert into public.refai_credit_accounts(user_id,balance) values(p_user_id,greatest(0,p_free_credits)) on conflict do nothing; select * into v_op from public.refai_credit_operations where user_id=p_user_id and operation_key=p_operation_key; if v_op.id is not null then select balance into v_balance from public.refai_credit_accounts where user_id=p_user_id; return jsonb_build_object('ok',true,'balance',v_balance,'replay',true); end if; select balance into v_balance from public.refai_credit_accounts where user_id=p_user_id for update; insert into public.refai_credit_operations(user_id,action,operation_key,cost,status) values(p_user_id,'simulated_purchase_'||p_plan,p_operation_key,p_credits,'completed') returning * into v_op; update public.refai_credit_accounts set balance=balance+p_credits,updated_at=now() where user_id=p_user_id returning balance into v_balance; insert into public.refai_credit_ledger(user_id,operation_id,action,amount,balance_after) values(p_user_id,v_op.id,'simulated_purchase_'||p_plan,p_credits,v_balance); return jsonb_build_object('ok',true,'balance',v_balance,'replay',false); end $$;
revoke all on function public.purchase_refai_credits(uuid,text,text,integer,integer) from public,anon,authenticated; grant execute on function public.purchase_refai_credits(uuid,text,text,integer,integer) to service_role;
