-- Persist grounded advisory Copilot summaries for the assigned employee only.
-- The input_key is an opaque SHA-256 fingerprint generated by FastAPI; no resume
-- text, prompts, provider metadata, or access tokens are stored in this table.
create table if not exists public.employee_review_copilot_cache (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.profiles(id) on delete cascade,
  referral_request_id uuid not null references public.referral_requests(id) on delete cascade,
  input_key text not null check (input_key ~ '^[0-9a-f]{64}$'),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_id, referral_request_id, input_key)
);

create index if not exists employee_review_copilot_cache_lookup_idx
  on public.employee_review_copilot_cache(employee_id, referral_request_id, input_key);

alter table public.employee_review_copilot_cache enable row level security;

drop policy if exists employee_review_copilot_cache_employee_read on public.employee_review_copilot_cache;
create policy employee_review_copilot_cache_employee_read
  on public.employee_review_copilot_cache for select to authenticated
  using (employee_id = auth.uid());

revoke all on public.employee_review_copilot_cache from anon, authenticated;
grant select on public.employee_review_copilot_cache to authenticated;
grant all on public.employee_review_copilot_cache to service_role;

create or replace function public.set_employee_review_copilot_cache_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists employee_review_copilot_cache_set_updated_at on public.employee_review_copilot_cache;
create trigger employee_review_copilot_cache_set_updated_at
before update on public.employee_review_copilot_cache
for each row execute function public.set_employee_review_copilot_cache_updated_at();
