-- Structured, student-safe referral decisions with employee-private notes.
alter table public.referral_requests
  add column if not exists decision_reason text,
  add column if not exists decision_message text,
  add column if not exists decision_at timestamptz;

alter table public.referral_status_history
  add column if not exists decision_reason text,
  add column if not exists decision_message text;

create table if not exists public.referral_decision_private_notes (
  id bigint generated by default as identity primary key,
  referral_request_id uuid not null references public.referral_requests(id) on delete cascade,
  employee_id uuid not null references public.profiles(id) on delete cascade,
  decision_status text not null,
  decision_reason text not null,
  note text not null,
  created_at timestamptz not null default now(),
  constraint referral_private_note_length check (length(trim(note)) between 1 and 2000)
);

create index if not exists referral_private_notes_request_idx
  on public.referral_decision_private_notes(referral_request_id, created_at desc);

alter table public.referral_decision_private_notes enable row level security;
drop policy if exists referral_private_notes_employee_read on public.referral_decision_private_notes;
create policy referral_private_notes_employee_read on public.referral_decision_private_notes
  for select to authenticated using (employee_id = auth.uid());
revoke all on public.referral_decision_private_notes from anon, authenticated;
grant select on public.referral_decision_private_notes to authenticated;
grant all on public.referral_decision_private_notes to service_role;

-- Move legacy request notes out of the student-readable request row.
insert into public.referral_decision_private_notes(
  referral_request_id, employee_id, decision_status, decision_reason, note, created_at
)
select id, employee_id, status::text, 'legacy_unstructured', employee_note, updated_at
from public.referral_requests
where employee_note is not null and length(trim(employee_note)) > 0
  and not exists (
    select 1 from public.referral_decision_private_notes n
    where n.referral_request_id = referral_requests.id and n.note = referral_requests.employee_note
  );
update public.referral_requests set employee_note = null where employee_note is not null;

create or replace function public.transition_structured_referral_decision_as(
  p_actor_id uuid, p_request_id uuid, p_new_status public.referral_status,
  p_reason text, p_decision_message text, p_private_note text default null
) returns public.referral_requests language plpgsql security definer set search_path = public as $$
declare
  v_request public.referral_requests;
  v_previous text;
  v_status_type text;
begin
  if not exists (select 1 from public.profiles where id = p_actor_id and role::text = 'employee') then
    raise exception 'employee access required' using errcode = '42501';
  end if;
  select * into v_request from public.referral_requests where id = p_request_id for update;
  if v_request.id is null then raise exception 'referral request not found'; end if;
  if v_request.employee_id <> p_actor_id then raise exception 'request is assigned to another employee' using errcode = '42501'; end if;
  v_previous := v_request.status::text;
  if not (
    (v_previous = 'pending' and p_new_status::text in ('under_review','more_info_requested','approved','declined')) or
    (v_previous = 'under_review' and p_new_status::text in ('more_info_requested','approved','declined')) or
    (v_previous = 'more_info_requested' and p_new_status::text in ('under_review','declined')) or
    (v_previous = 'approved' and p_new_status::text = 'referred')
  ) then raise exception 'invalid referral status transition'; end if;
  if p_new_status::text = 'approved' and p_reason not in ('suitable_profile','strong_evidence','relevant_role_alignment','will_refer_externally','additional_details_required_first') then
    raise exception 'invalid approve reason';
  elsif p_new_status::text = 'declined' and p_reason not in ('role_mismatch','insufficient_evidence','not_accepting_referrals','job_closed','unable_to_verify_experience','other') then
    raise exception 'invalid decline reason';
  elsif p_new_status::text = 'more_info_requested' and p_reason <> 'clarification_required' then
    raise exception 'invalid more-information reason';
  end if;
  if length(trim(coalesce(p_decision_message, ''))) < 1 then raise exception 'student-safe decision message required'; end if;

  select udt_name into v_status_type from information_schema.columns
    where table_schema = 'public' and table_name = 'referral_requests' and column_name = 'status';
  if v_status_type = 'referral_status' then
    execute 'update public.referral_requests set status = $1, employee_note = null, decision_reason = $2, decision_message = $3, decision_at = now(), updated_at = now() where id = $4 returning *'
      into v_request using p_new_status, p_reason, p_decision_message, p_request_id;
  else
    execute 'update public.referral_requests set status = $1::text, employee_note = null, decision_reason = $2, decision_message = $3, decision_at = now(), updated_at = now() where id = $4 returning *'
      into v_request using p_new_status, p_reason, p_decision_message, p_request_id;
  end if;

  perform public.refai_append_referral_status(p_request_id, v_previous, p_new_status::text, p_actor_id, null);
  update public.referral_status_history
  set decision_reason = p_reason, decision_message = p_decision_message
  where id = (
    select id from public.referral_status_history
    where referral_request_id = p_request_id and changed_by = p_actor_id
    order by created_at desc, id desc limit 1
  );
  if p_private_note is not null and length(trim(p_private_note)) > 0 then
    insert into public.referral_decision_private_notes(
      referral_request_id, employee_id, decision_status, decision_reason, note
    ) values (p_request_id, p_actor_id, p_new_status::text, p_reason, trim(p_private_note));
  end if;
  return v_request;
end $$;

revoke execute on function public.transition_structured_referral_decision_as(uuid, uuid, public.referral_status, text, text, text) from public, anon, authenticated;
grant execute on function public.transition_structured_referral_decision_as(uuid, uuid, public.referral_status, text, text, text) to service_role;
